name: parking_optimization
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - folium>=0.12.0
  - scikit-learn>=1.0.0
  - requests>=2.25.0
  - pytest>=7.0.0  # Testing framework (conda)
  - pytest-cov>=4.0.0  # Coverage reporting (conda)
  - mypy>=1.0.0  # Type checking (conda)
  - ruff>=0.1.0  # Fast Python linter and formatter (conda)
  - osmnx
  - geopandas
  - rtree
  - pip
  - pip:
    - pytest-benchmark>=4.0.0  # Performance benchmarking (pip only)
    - python-dotenv>=0.19.0  # Environment variables (pip only)
    - memory-profiler>=0.60.0  # Memory profiling (pip only)
    - pre-commit>=3.0.0  # Git hooks (pip only)